### ISSUE TITLE
Min Soc (on grid)

### ISSUE THREAD

**Issue by TonyM1958** [alpriest/EnergyStats-Android#1]
Great app. For most people, the effective min soc is on grid. Is it possible to display / use this instead of min soc, either directly or via a settings switch?

**Comment by alpriest** [comment]
Hi, that makes sense. I'm not sure I understand the difference but it's the same value for me so i'll drop an update out for that.

**Comment by alpriest** [comment]
Oh, just found a write up https://foxesscommunity.com/viewtopic.php?t=193 - yep minGridSoc makes more sense.

**Comment by TonyM1958** [comment]
Thanks. There's more info here, if that helps: [Battery Management](https://github.com/TonyM1958/HA-FoxESS-Modbus/wiki/Battery-Management)
