### ISSUE TITLE
month selection in stats

### ISSUE THREAD

**Issue by TonyM1958** [alpriest/EnergyStats-Android#12]
Minor issue with v1.46

If you select Month in Stats and then select a month e.g. June, the data for June is returned.
When you press the month again, instead of June, May is ticked in the list picker.
June is displayed on the button and data for June is being shown.

**Comment by alpriest** [comment]
Thanks, fixed in v1.48 just pushed for review.

**Comment by TonyM1958** [comment]
Thanks - took an hour or 2 for the update to appear on the Android Play Store, but I've now downloaded v.148 and it's fixed.
