### ISSUE TITLE
Battery Charge Schedule Messages

### ISSUE THREAD

**Issue by Wiggy93** [alpriest/EnergyStats-Android#13]
If both time periods are used and are not the same type (ie both force charge or both disable discharge/charge), only 1 of the descriptions is shown e.g.

"Your battery will be force charged from the grid between 03:00 to 04:45"

instead of 

"Your battery will be force charged from the grid between 03:00 to 04:45  and will not charge or discharge between 04:45 to 05:00"

**Comment by alpriest** [comment]
Thanks, this is done in 1.58 coming out shortly

**Comment by Wiggy93** [comment]
Great thanks!
