### ISSUE TITLE
Stats month does not display correctly

### ISSUE THREAD

**Issue by TonyM1958** [alpriest/EnergyStats-Android#2]
Select Stats and Month. Browse months, the order is January, March, March, May, May. February and April sometimes appear in the drop down but are not displayed when selected.

This is February:

![Screenshot_20230531-073733_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/c2569dff-61fd-4e0c-a676-37cf7198cd19)

![Screenshot_20230531-073742_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/d73b7754-2ffc-4821-af0a-2e7c76fe80a4)

This is April:

![Screenshot_20230531-073755_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/d2611376-d341-475a-8130-e448eac8c9cb)

![Screenshot_20230531-073724_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/262a9281-e795-4d6e-b175-487902a7dedb)

![Screenshot_20230531-073708_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/00ce7346-f534-40eb-84dc-a3349ef64991)

![Screenshot_20230531-074748_Energy Stats](https://github.com/alpriest/EnergyStats-Android/assets/63789168/410f1a6d-6217-44e4-a3c8-3c19f3b9d062)

**Comment by alpriest** [comment]
Thanks, looks like the app was subtracting 1 month from the current date (31st May), getting 31st April which is invalid and sticking with May. Not sure why it didn't crash completely.

Fix just pushed to the Play store.

**Comment by TonyM1958** [comment]
Thanks - obvious now you said it, that these are the months that don't have 31 days! Just luck I suppose that I looked at it today...
