### ISSUE TITLE
Raw data from 04/11/2023

### ISSUE THREAD

**Issue by TonyM1958** [alpriest/EnergyStats-Android#20]
Just a quick heads up - with the cloud outage last night, some of the raw data samples are AWOL today.

For example, some of the samples are 10 minutes apart instead of 5 minutes.

Depending how you generate your X co-ord for plotting, this may throw out some of the data - in case any notices or queries this?

**Comment by alpriest** [comment]
All looks good thanks on my persoanl data I can't see any outages. Both iOS and Android cope fine with missing values on their scales 👍
