### ISSUE TITLE
Wording of "battery freeze" charge schedule message

### ISSUE THREAD

**Issue by spco** [alpriest/EnergyStats-Android#22]
When setting the battery charge schedule to a non-zero time period, but with the "enable charge from grid" toggle disabled, the following message displays:

`"Your batteries will not charge or discharge between 12:00 and 16:00. Any house load will come from the grid between these times. Reset the time period to disable this."`

In my experience, this wording is incorrect, because the batteries _will_ charge from the solar panels, but not from the grid. Essentially, this setting diverts all the solar power to charging the battery, rather than the house. I'd welcome any independent confirmation of this, in case it's dependent on another setting my system has.

This is a screenshot with it enabled:
![Screenshot_2023-11-21-11-09-46-95_4bfa71e7083cdea1ef7828997a9b5f8f](https://github.com/alpriest/EnergyStats-Android/assets/11610738/2f9b5812-9767-44d2-b6fa-9b77c464e546)

I'd suggest:
`"Your batteries will not discharge between 12:00 and 16:00. Any house load will come from the grid between these times. Reset the time period to disable this."`
or perhaps something like:
`"Your batteries will not discharge between 12:00 and 16:00. Solar power will be diverted to charging the battery. Any house load will come from the grid between these times. Reset the time period to disable this."`

The affected strings (in English) are https://github.com/alpriest/EnergyStats-Android/blob/a6b841106d71add895e689d1a8a4c525beed4e6a/app/src/main/res/values/strings.xml#L141-L142

TIA!

**Comment by alpriest** [comment]
Hi, thanks for the super descriptive report. This was added in a recent version to both [iOS](https://github.com/alpriest/EnergyStats) and Android apps.
