### ISSUE TITLE
Group charts in Parameters by units

### ISSUE THREAD

**Issue by TonyM1958** [alpriest/EnergyStats-Android#6]
I think you said it was early days for Parameters, so you may already be working on things...  just let me know if you have enough ideas and suggestions already! None of these are urgent.

When you select a variety of parameters, the vertical axis of the chart currently mixes values. Suggestions:

1. add the units to the selection list to make it a bit obvious which items work together
2. group the parameters selected by units and display on different charts with the unit displayed on the axis

So, if you select PV1/PV2 Voltage, PV1/PV2 Current (for example), each parameter is displayed with an appropriately scaled vertical axis. Or, if you select a range of power values and temperatures, the temps appear on a separate chart with C. The horizontal axis of the charts are synchronised, of course.

Off the top of my head, I think there are 5 potential charts based on %, voltage, current, power and temperature?

Also when selecting 'Compare Strings' include PV Power as well as PV1, PV2, PV3 and PV4 power so you get the total power as well as the individual contributions.

**Comment by alpriest** [comment]
It's early days, but my todo list for parameters was empty :)

I've just pushed an update to append the Unit alongside the parameter to make it easier to see. Grouping the parameters by Unit makes sense too i've just got to figure a pleasant way to display the visiblity/summary toggles beneath the chart.

Also I'm not entirely sure how FoxESS run their rate limiting algorithm and whether they take data volumes into account. I might consider fetching all variable values and then making the UI purely an in-memory display to reduce load. There'd be a small issue to determine when a new fetch is required but it's reasonably trivial.

**Comment by TonyM1958** [comment]
BTW - not holding this up as the best example, but I added some plotting functions to my cloud library. Feel free to have a look through the code if you want to see how it works - sure you will be do it better though! Couple of examples:

![image](https://github.com/alpriest/EnergyStats-Android/assets/63789168/f15772ee-eff6-4b37-bad8-e45d690bb744)

![image](https://github.com/alpriest/EnergyStats-Android/assets/63789168/6bab4ed2-6602-4299-b355-f5b01ed73256)

![image](https://github.com/alpriest/EnergyStats-Android/assets/63789168/78c68973-8d38-4237-abe9-afe780078372)

**Comment by alpriest** [comment]
This was added recently.
